


image bg black = "images/backgrounds/Black.png"
image black = "images/backgrounds/Black.png"
image bg fade black = "images/backgrounds/fade_black.png"
image bg white = "images/backgrounds/White.png"
image bg fade white = "images/backgrounds/fade_white.png"
image bg broom_day = "images/backgrounds/bedroom_day.png"
image bg broom_day_shut = "images/backgrounds/bedroom_day_shutters.png"
image bg broom_day_in = "images/backgrounds/bedroom_day_in.png"
image bg broom_light = "images/backgrounds/bedroom_light.png"
image bg broom_night = "images/backgrounds/bedroom_night.png"
image bg window_day = "images/backgrounds/window_day.png"
image bg window_night = "images/backgrounds/window_night.png"
image bg window_rain = "images/backgrounds/window_rain.png"
image bg outdoor_d = "images/backgrounds/outdoors_day.png"
image bg outdoor_n = "images/backgrounds/outdoors_night.png"
image bg outdoor_r = "images/backgrounds/outdoors_rain.png"
image bg kitchen_day = "images/backgrounds/kitchen_day.png"
image bg kitchen_day_fire = "images/backgrounds/kitchen_day_fire.png"
image bg kitchen_night = "images/backgrounds/kitchen_night.png"
image bg kitchen_nightmare = "images/backgrounds/kitchen_nightmare.png"
image bg kitchen_light = "images/backgrounds/kitchen_night_fire.png"
image bg credit = "images/backgrounds/credits.png"
image bg cottage side day = "images/backgrounds/cottage_side_day.png"
image bg cottage side night = "images/backgrounds/cottage_side_night.png"
image bg cottage side rain = "images/backgrounds/cottage_side_rain.png"
image bg cottage front day = "images/backgrounds/cottage_front_day.png"
image bg cottage front eve = "images/backgrounds/cottage_front_evening.png"
image bg cottage front night = "images/backgrounds/cottage_front_night.png"
image bg cottage front night dark = "images/backgrounds/cottage_front_night_dark.png"
image bg glade day = "images/backgrounds/glade_day.png"
image bg glade day bow = "images/backgrounds/glade_day_bow.png"
image bg glade rain = "images/backgrounds/glade_rain.png"
image bg village street day = "images/backgrounds/village_street_day.png"
image bg village street eve = "images/backgrounds/village_street_evening.png"
image bg village centre day = "images/backgrounds/village_centre_day.png"
image bg village centre eve = "images/backgrounds/village_centre_eve.png"
image bg villa front = "images/backgrounds/villa_front.png"
image bg villa atrium = "images/backgrounds/villa_atrium.png"
image bg villa hall = "images/backgrounds/villa_hall.png"
image bg villa pantry = "images/backgrounds/villa_pantry.png"
image bg feast_eve = "images/backgrounds/feast_evening.png"
image bg feast_night = "images/backgrounds/feast_night.png"
image bg moon_shrine_night = "images/backgrounds/moon_shrine_night.png"
image bg feast_table = "images/backgrounds/feast_table.png"
image bg butchery shop = "images/backgrounds/butchery_shop.png"
image bg butchery backroom = "images/backgrounds/butchery_backroom.png"
image bg sylvan road = "images/backgrounds/sylvan_road.png"
image bg forest_stream = "images/backgrounds/forest_stream.png"


image choking = "images/illustrations/choking.png"
image fight_1 = "images/illustrations/fight_1.png"
image blade = "images/illustrations/blade.png"
image breakfast_1 = "images/illustrations/breakfast_1.png"
image breakfast_2 = "images/illustrations/breakfast_2.png"
image breakfast_3 = "images/illustrations/breakfast_3.png"
image breakfast_4 = "images/illustrations/breakfast_4.png"
image breakfast_5 = "images/illustrations/breakfast_5.png"
image breakfast_6 = "images/illustrations/breakfast_6.png"
image breakfast_table_1 = "images/illustrations/breakfast_table_1.png"
image breakfast_table_2 = "images/illustrations/breakfast_table_2.png"
image breakfast_table_3 = "images/illustrations/breakfast_table_3.png"
image breakfast_table_4 = "images/illustrations/breakfast_table_4.png"
image breakfast_table_5 = "images/illustrations/breakfast_table_5.png"
image breakfast_table_6 = "images/illustrations/breakfast_table_6.png"
image breakfast_table_7 = "images/illustrations/breakfast_table_7.png"
image waterbowl = "images/illustrations/waterbowl.png"
image waterbowl_light = "images/illustrations/waterbowl_light.png"
image stabbed = "images/illustrations/stabbed.png"
image found = "images/illustrations/found.png"
image night_guard = "images/illustrations/night_guard.png"
image ran_splayed = "images/illustrations/ran_splayed.png"
image ran_splayed_e = "images/illustrations/ran_splayed_e.png"
image ran_splayed_brow = "images/illustrations/ran_splayed_brow.png"
image ran_splayed_laugh = "images/illustrations/ran_splayed_laugh.png"
image ran_splayed_neutral = "images/illustrations/ran_splayed_neutral.png"
image ran_splayed_sad = "images/illustrations/ran_splayed_sad.png"
image ran_splayed_sigh = "images/illustrations/ran_splayed_sigh.png"
image ran_splayed_smile = "images/illustrations/ran_splayed_smile.png"
image ran_splayed_smile_en = "images/illustrations/ran_splayed_smile_en.png"
image ran_splayed_talk = "images/illustrations/ran_splayed_talk.png"
image ran_splayed_unhappy = "images/illustrations/ran_splayed_unhappy.png"
image ran_splayed_shocked = "images/illustrations/ran_splayed_shocked.png"
image sleeping = "images/illustrations/sleeping.png"
image sleeping_smile = "images/illustrations/sleeping_smile.png"
image stew = "images/illustrations/stew.png"
image stew_pale = "images/illustrations/stew_pale.png"
image ran_window = "images/illustrations/ran_window.png"
image ran_window_blush = "images/illustrations/ran_window_blush.png"
image ran_meadow_1 = "images/illustrations/ran_meadow_1.png"
image ran_meadow_2 = "images/illustrations/ran_meadow_2.png"
image ran_meadow_3 = "images/illustrations/ran_meadow_3.png"
image ran_meadow_4 = "images/illustrations/ran_meadow_4.png"
image ran_meadow_5 = "images/illustrations/ran_meadow_5.png"
image ran_meadow_6 = "images/illustrations/ran_meadow_6.png"
image ran_meadow_7 = "images/illustrations/ran_meadow_7.png"
image ran_meadow_8 = "images/illustrations/ran_meadow_8.png"
image dandelion_1 = "images/illustrations/dandelion_1.png"
image dandelion_2 = "images/illustrations/dandelion_2.png"
image dandelion_3 = "images/illustrations/dandelion_3.png"
image pastries = "images/illustrations/pastries.png"
image bench = "images/illustrations/bench.png"
image heart_to_heart = "images/illustrations/heart_to_heart.png"
image heart_to_heart_one = "images/illustrations/heart_to_heart_1.png"
image heart_to_heart_two = "images/illustrations/heart_to_heart_2.png"
image heart_to_heart_three = "images/illustrations/heart_to_heart_3.png"
image heart_to_heart_four = "images/illustrations/heart_to_heart_4.png"
image collar = "images/illustrations/collar.png"


image ran c annoyed = "images/sprites/ranok/ranok annoyed.png"
image ran c annoyed e = "images/sprites/ranok/ranok annoyed e.png"
image ran c annoyed r paw = "images/sprites/ranok/ranok annoyed r paw.png"
image ran c annoyed r = "images/sprites/ranok/ranok annoyed r.png"
image ran c annoyed rt = "images/sprites/ranok/ranok annoyed rt.png"
image ran c annoyed rtp = "images/sprites/ranok/ran_annoyed_rtp.png"
image ran c annoyed t = "images/sprites/ranok/ran_annoyed_t.png"
image ran c annoyed tp = "images/sprites/ranok/ran_annoyed_tp.png"
image ran c awkward = "images/sprites/ranok/ranok awkward.png"
image ran c awkward hard = "images/sprites/ranok/ranok awkward hard.png"
image ran c awkward shrug = "images/sprites/ranok/ran_awkward_shrug.png"
image ran c awkward rt = "images/sprites/ranok/ran_awkward_rt.png"
image ran c awkward rte = "images/sprites/ranok/ran_awkward_rte.png"
image ran c awkward s = "images/sprites/ranok/ran_awkward_s.png"
image ran c awkward rs = "images/sprites/ranok/ran_awkward_rs.png"
image ran c awkward rpe = "images/sprites/ranok/ran_awkward_rpe.png"
image ran c bleep = "images/sprites/ranok/ran_bleep.png"
image ran c bemused = "images/sprites/ranok/ranok bemused.png"
image ran c bemused r = "images/sprites/ranok/ranok bemused r.png"
image ran c confused = "images/sprites/ranok/ranok confused.png"
image ran c confused t = "images/sprites/ranok/ranok confused t.png"
image ran c confused paw = "images/sprites/ranok/ranok confused paw.png"
image ran c doubtful = "images/sprites/ranok/ranok doubtful.png"
image ran c doubtful paw = "images/sprites/ranok/ranok doubtful paw.png"
image ran c embarrassed = "images/sprites/ranok/ranok embarrassed.png"
image ran c embarrassed blush = "images/sprites/ranok/ranok embarrassed blush.png"
image ran c embarrassed e = "images/sprites/ranok/ranok embarrassed e.png"
image ran c embarrassed e relax = "images/sprites/ranok/ranok embaressed e relax.png"
image ran c embarrassed shrug = "images/sprites/ranok/ranok embarrassed shrug.png"
image ran c embarrassed t = "images/sprites/ranok/ranok embarrassed t.png"
image ran c embarrassed te = "images/sprites/ranok/ranok embarrassed te.png"
image ran c excited = "images/sprites/ranok/ran_excited.png"
image ran c eyeroll = "images/sprites/ranok/ranok eyeroll.png"
image ran c facepalm = "images/sprites/ranok/ranok facepalm.png"
image ran c growl = "images/sprites/ranok/ranok growl.png"
image ran c growl hard = "images/sprites/ranok/ran_growl_hard.png"
image ran c growl paw = "images/sprites/ranok/ranok growl paw.png"
image ran c growl r paw = "images/sprites/ranok/ranok growl r paw.png"
image ran c growl r = "images/sprites/ranok/ranok growl r.png"
image ran c laugh = "images/sprites/ranok/ranok laugh.png"
image ran c lol = "images/sprites/ranok/ranok lol.png"
image ran c look up = "images/sprites/ranok/ran_look_up.png"
image ran c mutter paw = "images/sprites/ranok/ranok mutter paw.png"
image ran c mutter r = "images/sprites/ranok/ranok mutter r.png"
image ran c neutral = "images/sprites/ranok/ranok neutral.png"
image ran c neutral e = "images/sprites/ranok/ranok neutral e.png"
image ran c neutral et = "images/sprites/ranok/ranok neutral et.png"
image ran c neutral hip = "images/sprites/ranok/ranok neutral hip.png"
image ran c neutral rt paw = "images/sprites/ranok/ranok neutral r t paw.png"
image ran c neutral re = "images/sprites/ranok/ranok neutral re.png"
image ran c neutral rt = "images/sprites/ranok/ranok neutral r t.png"
image ran c neutral rte = "images/sprites/ranok/ranok neutral rte.png"
image ran c neutral r = "images/sprites/ranok/ranok neutral r.png"
image ran c neutral t paw = "images/sprites/ranok/ranok neutral t paw.png"
image ran c neutral t = "images/sprites/ranok/ranok neutral t.png"
image ran c ok = "images/sprites/ranok/ranok ok.png"
image ran c ok wink = "images/sprites/ranok/ranok ok wink.png"
image ran c pouty = "images/sprites/ranok/ranok pouty.png"
image ran c pouty hard = "images/sprites/ranok/ranok pouty hard.png"
image ran c pouty paw = "images/sprites/ranok/ranok pouty paw.png"
image ran c resigned = "images/sprites/ranok/ranok resigned.png"
image ran c sigh = "images/sprites/ranok/ranok sigh.png"
image ran c sad = "images/sprites/ranok/ranok sad.png"
image ran c sad e = "images/sprites/ranok/ranok sad e.png"
image ran c sad t = "images/sprites/ranok/ranok sad t.png"
image ran c sad te = "images/sprites/ranok/ranok sad te.png"
image ran c sad rt = "images/sprites/ranok/ran_sad_rt.png"
image ran c sad tp = "images/sprites/ranok/ran_sad_tp.png"
image ran c serious = "images/sprites/ranok/ranok serious.png"
image ran c serious t = "images/sprites/ranok/ranok serious t.png"
image ran c shocked = "images/sprites/ranok/ranok shocked.png"
image ran c shocked blush = "images/sprites/ranok/ranok shocked blush.png"
image ran c shocked r = "images/sprites/ranok/ranok shocked r.png"
image ran c shrug r = "images/sprites/ranok/ran_shrug_r.png"
image ran c shrug e = "images/sprites/ranok/ran_shrug_e.png"
image ran c smile = "images/sprites/ranok/ranok smile.png"
image ran c smile blush = "images/sprites/ranok/ran_smile_blush.png"
image ran c smile e paw = "images/sprites/ranok/ranok smile e paw.png"
image ran c smile e = "images/sprites/ranok/ranok smile e.png"
image ran c smile e relax = "images/sprites/ranok/ranok smile e relax.png"
image ran c smile hip paw = "images/sprites/ranok/ranok smile hip paw.png"
image ran c smile hip = "images/sprites/ranok/ranok smile hip.png"
image ran c smile re paw = "images/sprites/ranok/ranok smile r e paw.png"
image ran c smile re = "images/sprites/ranok/ranok smile r e.png"
image ran c smile r paw = "images/sprites/ranok/ranok smile r paw.png"
image ran c smile r = "images/sprites/ranok/ranok smile r.png"
image ran c smile sly = "images/sprites/ranok/ran_smile_sly.png"
image ran c smile sweet = "images/sprites/ranok/ran_smile_sweet.png"
image ran c talk g = "images/sprites/ranok/ran_talk_g.png"
image ran c talk gs = "images/sprites/ranok/ran_talk_gs.png"
image ran c smirk re = "images/sprites/ranok/ranok smirk re.png"
image ran c smile re c = "images/sprites/ranok/ranok smile re c.png"
image ran c smirk = "images/sprites/ranok/ranok smirk.png"
image ran c smirk paw = "images/sprites/ranok/ranok smirk paw.png"
image ran c smirk shrug = "images/sprites/ranok/ranok smirk shrug.png"
image ran c startled = "images/sprites/ranok/ranok startled.png"
image ran c talk = "images/sprites/ranok/ranok talk.png"
image ran c talk e = "images/sprites/ranok/ranok talk e.png"
image ran c talk paw = "images/sprites/ranok/ranok talk paw.png"
image ran c talk e paw = "images/sprites/ranok/ranok talk e paw.png"
image ran c talk r paw = "images/sprites/ranok/ranok talk r paw.png"
image ran c talk r = "images/sprites/ranok/ranok talk r.png"
image ran c think = "images/sprites/ranok/ranok thinking.png"
image ran c wink = "images/sprites/ranok/ranok wink.png"
image ran c worried rt paw = "images/sprites/ranok/ranok worried r t paw.png"
image ran c worried rt = "images/sprites/ranok/ranok worried r t.png"
image ran c worried r = "images/sprites/ranok/ranok worried r.png"
image ran c left smile = "images/sprites/ranok/ran_left_smile.png"
image ran c left smile l = "images/sprites/ranok/ran_left_smile_l.png"
image ran c left smile e = "images/sprites/ranok/ran_left_smile_e.png"
image ran c left talk l = "images/sprites/ranok/ran_left_talk_l.png"
image ran c left smirk = "images/sprites/ranok/ran_left_smirk.png"


image ran pan awkward = "images/sprites/ranok_cook/ran_pan_awkward.png"
image ran pan excited = "images/sprites/ranok_cook/ran_pan_excited.png"
image ran pan neutral r = "images/sprites/ranok_cook/ran_pan_neutral_r.png"
image ran pan shocked blush = "images/sprites/ranok_cook/ran_pan_shocked_blush.png"
image ran pan smile = "images/sprites/ranok_cook/ran_pan_smile.png"
image ran pan smile e = "images/sprites/ranok_cook/ran_pan_smile_e.png"
image ran pan smirk = "images/sprites/ranok_cook/ran_pan_smirk.png"
image ran pan talk = "images/sprites/ranok_cook/ran_pan_talk.png"
image ran pan talk e = "images/sprites/ranok_cook/ran_pan_talk_e.png"
image ran pan talk g = "images/sprites/ranok_cook/ran_pan_talk_g.png"
image ran pan flip = "images/sprites/ranok_cook/ran_pan_flip.png"
image ran pan wink = "images/sprites/ranok_cook/ran_pan_wink.png"
image ran pan flip s = "images/sprites/ranok_cook/ran_pan_flip_s.png"


image ran p ang r = "images/sprites/ranok_pants/ran_ang_r.png"
image ran p ang re = "images/sprites/ranok_pants/ran_ang_re.png"
image ran p ang rt = "images/sprites/ranok_pants/ran_ang_rt.png"
image ran p annoyed = "images/sprites/ranok_pants/ran_annoyed.png"
image ran p annoyed x = "images/sprites/ranok_pants/ran_annoyed_x.png"
image ran p annoyed e = "images/sprites/ranok_pants/ran_annoyed_e.png"
image ran p annoyed t = "images/sprites/ranok_pants/ran_annoyed_t.png"
image ran p annoyed tp = "images/sprites/ranok_pants/ran_annoyed_tp.png"
image ran p awkward = "images/sprites/ranok_pants/ran_awkward.png"
image ran p awkward hard = "images/sprites/ranok_pants/ran_awkward_hard.png"
image ran p awkward s = "images/sprites/ranok_pants/ran_awkward_s.png"
image ran p bemused = "images/sprites/ranok_pants/ran_bemused.png"
image ran p bemused t = "images/sprites/ranok_pants/ran_bemused_t.png"
image ran p confused = "images/sprites/ranok_pants/ran_confused.png"
image ran p confused pt = "images/sprites/ranok_pants/ran_confused_pt.png"
image ran p eyeroll = "images/sprites/ranok_pants/ran_eyeroll.png"
image ran p eyeroll s = "images/sprites/ranok_pants/ran_eyeroll_s.png"
image ran p embarrassed = "images/sprites/ranok_pants/ran_embarrassed.png"
image ran p embarrassed blush = "images/sprites/ranok_pants/ran_embarrassed_blush.png"
image ran p embarrassed t = "images/sprites/ranok_pants/ran_embarrassed_t.png"
image ran p growl = "images/sprites/ranok_pants/ran_growl.png"
image ran p growl p = "images/sprites/ranok_pants/ran_growl_p.png"
image ran p growl r = "images/sprites/ranok_pants/ran_growl_r.png"
image ran p growl rp = "images/sprites/ranok_pants/ran_growl_rp.png"
image ran p growl s = "images/sprites/ranok_pants/ran_growl_s.png"
image ran p growl hard = "images/sprites/ranok_pants/ran_growl_hard.png"
image ran p howl = "images/sprites/ranok_pants/ran_howl.png"
image ran p laugh x = "images/sprites/ranok_pants/ran_laugh_x.png"
image ran p lol = "images/sprites/ranok_pants/ran_lol.png"
image ran p smile e = "images/sprites/ranok_pants/ran_smile_e.png"
image ran p smile eh = "images/sprites/ranok_pants/ran_smile_eh.png"
image ran p smile ex = "images/sprites/ranok_pants/ran_smile_ex.png"
image ran p smile r = "images/sprites/ranok_pants/ran_smile_r.png"
image ran p smile rte shrug = "images/sprites/ranok_pants/ran_smile_rte_shrug.png"
image ran p smile = "images/sprites/ranok_pants/ran_smile.png"
image ran p smile s = "images/sprites/ranok_pants/ran_smile_s.png"
image ran p smile sp = "images/sprites/ranok_pants/ran_smile_sp.png"
image ran p smile x = "images/sprites/ranok_pants/ran_smile_x.png"
image ran p smile v = "images/sprites/ranok_pants/ran_smile_v.png"
image ran p smile blush = "images/sprites/ranok_pants/ran_smile_blush.png"
image ran p shrug = "images/sprites/ranok_pants/ran_shrug.png"
image ran p smirk = "images/sprites/ranok_pants/ran_smirk.png"
image ran p sigh = "images/sprites/ranok_pants/ran_sigh.png"
image ran p sad = "images/sprites/ranok_pants/ran_sad.png"
image ran p sad e = "images/sprites/ranok_pants/ran_sad_e.png"
image ran p sad t = "images/sprites/ranok_pants/ran_sad_t.png"
image ran p sad tp = "images/sprites/ranok_pants/ran_sad_tp.png"
image ran p sad r = "images/sprites/ranok_pants/ran_sad_r.png"
image ran p sad rt = "images/sprites/ranok_pants/ran_sad_rt.png"
image ran p sad rtp = "images/sprites/ranok_pants/ran_sad_rtp.png"
image ran p sad ret = "images/sprites/ranok_pants/ran_sad_ret.png"
image ran p shocked = "images/sprites/ranok_pants/ran_shocked.png"
image ran p shocked blush = "images/sprites/ranok_pants/ran_shocked_blush.png"
image ran p shocked r = "images/sprites/ranok_pants/ran_shocked_r.png"
image ran p shocked x = "images/sprites/ranok_pants/ran_shocked_x.png"
image ran p shocked xr = "images/sprites/ranok_pants/ran_shocked_xr.png"
image ran p struggle = "images/sprites/ranok_pants/ran_struggle.png"
image ran p wink = "images/sprites/ranok_pants/ran_wink.png"
image ran p talk = "images/sprites/ranok_pants/ran_talk.png"
image ran p talk blush = "images/sprites/ranok_pants/ran_talk_blush.png"
image ran p talk e = "images/sprites/ranok_pants/ran_talk_e.png"
image ran p talk g = "images/sprites/ranok_pants/ran_talk_g.png"
image ran p talk r = "images/sprites/ranok_pants/ran_talk_r.png"
image ran p talk p = "images/sprites/ranok_pants/ran_talk_p.png"
image ran p talk x = "images/sprites/ranok_pants/ran_talk_x.png"
image ran p think = "images/sprites/ranok_pants/ran_think.png"
image ran p neutral = "images/sprites/ranok_pants/ran_neutral.png"
image ran p neutral e = "images/sprites/ranok_pants/ran_neutral_e.png"
image ran p neutral h = "images/sprites/ranok_pants/ran_neutral_h.png"
image ran p neutral t = "images/sprites/ranok_pants/ran_neutral_t.png"
image ran p neutral r = "images/sprites/ranok_pants/ran_neutral_r.png"
image ran p neutral tr = "images/sprites/ranok_pants/ran_neutral_tr.png"
image ran p neutral te = "images/sprites/ranok_pants/ran_neutral_te.png"
image ran p neutral th = "images/sprites/ranok_pants/ran_neutral_th.png"
image ran p neutral thr = "images/sprites/ranok_pants/ran_neutral_thr.png"
image ran p neutral thrp = "images/sprites/ranok_pants/ran_neutral_thrp.png"
image ran p sad te = "images/sprites/ranok_pants/ran_sad_te.png"
image ran p stretch = "images/sprites/ranok_pants/ran_stretch.png"
image ran p pouty = "images/sprites/ranok_pants/ran_pouty.png"
image ran p pouty e = "images/sprites/ranok_pants/ran_pouty_e.png"
image ran p wtf = "images/sprites/ranok_pants/ran_wtf.png"
image ran p wth = "images/sprites/ranok_pants/ran_wth.png"


image ran u awkward = "images/sprites/ranok_undies/ran_awkward.png"
image ran u bemused = "images/sprites/ranok_undies/ran_bemused.png"
image ran u bemused t = "images/sprites/ranok_undies/ran_bemused_t.png"
image ran u neutral = "images/sprites/ranok_undies/ran_neutral.png"
image ran u sad = "images/sprites/ranok_undies/ran_sad.png"
image ran u sad t = "images/sprites/ranok_undies/ran_sad_t.png"
image ran u shocked = "images/sprites/ranok_undies/ran_shock.png"
image ran u shocked x = "images/sprites/ranok_undies/ran_shock_x.png"
image ran u shocked blush = "images/sprites/ranok_undies/ran_shock_blush.png"
image ran u shrug = "images/sprites/ranok_undies/ran_shrug.png"
image ran u smile = "images/sprites/ranok_undies/ran_smile.png"
image ran u smile e = "images/sprites/ranok_undies/ran_smile_e.png"
image ran u smile x = "images/sprites/ranok_undies/ran_smile_x.png"
image ran u smile xe = "images/sprites/ranok_undies/ran_smile_xe.png"
image ran u smirk = "images/sprites/ranok_undies/ran_smirk.png"
image ran u smirk rpe = "images/sprites/ranok_undies/ran_smirk_rpe.png"
image ran u stretch wet = "images/sprites/ranok_undies/ran_stretch_wet.png"
image ran u talk = "images/sprites/ranok_undies/ran_talk.png"
image ran u talk e = "images/sprites/ranok_undies/ran_talk_e.png"
image ran u talk p = "images/sprites/ranok_undies/ran_talk_paw.png"
image ran u talk x = "images/sprites/ranok_undies/ran_talk_x.png"


image ran n annoyed = "images/sprites/ranok_nude/ran_annoyed.png"
image ran n growl rp = "images/sprites/ranok_nude/ran_growl_rp.png"
image ran n growl soft = "images/sprites/ranok_nude/ran_growl_soft.png"
image ran n shocked = "images/sprites/ranok_nude/ran_shocked.png"
image ran n shocked = "images/sprites/ranok_nude/ran_shocked.png"
image ran n shocked = "images/sprites/ranok_nude/ran_shocked.png"
image ran n startled = "images/sprites/ranok_nude/ran_startled.png"
image ran n stretch = "images/sprites/ranok_nude/ran_stretch.png"
image ran n back = "images/sprites/ranok_nude/ran_back.png"
image ran n back blush = "images/sprites/ranok_nude/ran_back_blush.png"


image ran h awkward = "images/sprites/ranok_half/ran_awkward.png"
image ran h annoyed = "images/sprites/ranok_half/ran_annoyed.png"
image ran h annoyed t = "images/sprites/ranok_half/ran_annoyed_t.png"
image ran h embarrassed = "images/sprites/ranok_half/ran_embarrassed.png"
image ran h embarrassed blush = "images/sprites/ranok_half/ran_embarrassed_blush.png"
image ran h laugh = "images/sprites/ranok_half/ran_laugh.png"
image ran h smile = "images/sprites/ranok_half/ran_smile.png"
image ran h smile e = "images/sprites/ranok_half/ran_smile_e.png"
image ran h smirk = "images/sprites/ranok_half/ran_smirk.png"
image ran h talk = "images/sprites/ranok_half/ran_talk.png"
image ran h talk e = "images/sprites/ranok_half/ran_talk_e.png"
image ran h talk p = "images/sprites/ranok_half/ran_talk_p.png"
image ran h talk rp = "images/sprites/ranok_half/ran_talk_rp.png"
image ran h sad = "images/sprites/ranok_half/ran_sad.png"
image ran h sad e = "images/sprites/ranok_half/ran_sad_e.png"
image ran h sad t = "images/sprites/ranok_half/ran_sad_t.png"
image ran h think = "images/sprites/ranok_half/ran_think.png"
image ran h sad et = "images/sprites/ranok_half/ran_sad_et.png"
image ran h shocked = "images/sprites/ranok_half/ran_shocked.png"
image ran h shocked blush = "images/sprites/ranok_half/ran_shocked_blush.png"
image ran h neutral = "images/sprites/ranok_half/ran_neutral.png"
image ran h neutral e = "images/sprites/ranok_half/ran_neutral_e.png"
image ran h neutral t = "images/sprites/ranok_half/ran_neutral_t.png"
image ran h neutral et = "images/sprites/ranok_half/ran_neutral_et.png"
image ran h neutral ex = "images/sprites/ranok_half/ran_neutral_ex.png"
image ran h neutral ext = "images/sprites/ranok_half/ran_neutral_ext.png"
image ran h neutral tp = "images/sprites/ranok_half/ran_neutral_tp.png"
image ran h neutral rt = "images/sprites/ranok_half/ran_neutral_rt.png"
image ran h pouty = "images/sprites/ranok_half/ran_pouty.png"
image ran h confused = "images/sprites/ranok_half/ran_confused.png"


image vul amused = "images/sprites/vulgor/vulgor_amused_e.png"
image vul eyeroll = "images/sprites/vulgor/vulgor_eyeroll.png"
image vul facepalm = "images/sprites/vulgor/vulgor_facepalm.png"
image vul facepalm e = "images/sprites/vulgor/vulgor_facepalm_e.png"
image vul facepalm growl = "images/sprites/vulgor/vulgor_facepalm_growl.png"
image vul facepalm growl p = "images/sprites/vulgor/vulgor_facepalm_growl_p.png"
image vul growl = "images/sprites/vulgor/vulgor_growl.png"
image vul growl k = "images/sprites/vulgor/vulgor_growl_k.png"
image vul growl kl = "images/sprites/vulgor/vulgor_growl_kl.png"
image vul growl lx = "images/sprites/vulgor/vulgor_growl_lx.png"
image vul growl p = "images/sprites/vulgor/vulgor_growl_p.png"
image vul growl u = "images/sprites/vulgor/vulgor_growl_u.png"
image vul growl x = "images/sprites/vulgor/vulgor_growl_x.png"
image vul growl r = "images/sprites/vulgor/vul_growl_r.png"
image vul growl e = "images/sprites/vulgor/vul_growl_e.png"
image vul growl l = "images/sprites/vulgor/vul_growl_l.png"
image vul growl lp = "images/sprites/vulgor/vul_growl_lp.png"
image vul growl rk = "images/sprites/vulgor/vul_growl_rk.png"
image vul growl up = "images/sprites/vulgor/vul_growl_up.png"
image vul growl ux = "images/sprites/vulgor/vul_growl_ux.png"
image vul growl uh = "images/sprites/vulgor/vul_growl_uh.png"
image vul intrigued = "images/sprites/vulgor/vulgor_intrigued.png"
image vul intrigued l = "images/sprites/vulgor/vulgor_intrigued_l.png"
image vul intrigued tl = "images/sprites/vulgor/vulgor_intrigued_tl.png"
image vul intrigued x = "images/sprites/vulgor/vul_intrigued_x.png"
image vul neutral = "images/sprites/vulgor/vulgor_neutral.png"
image vul neutral e = "images/sprites/vulgor/vul_neutral_e.png"
image vul neutral ex = "images/sprites/vulgor/vul_neutral_ex.png"
image vul neutral l = "images/sprites/vulgor/vulgor_neutral_l.png"
image vul neutral r = "images/sprites/vulgor/vul_neutral_r.png"
image vul neutral rt = "images/sprites/vulgor/vul_neutral_rt.png"
image vul neutral x = "images/sprites/vulgor/vulgor_neutral_x.png"
image vul neutral xl = "images/sprites/vulgor/vul_neutral_xl.png"
image vul shocked = "images/sprites/vulgor/vulgor_shocked.png"
image vul shocked x = "images/sprites/vulgor/vulgor_shocked_x.png"
image vul sly l = "images/sprites/vulgor/vul_sly_l.png"
image vul sigh = "images/sprites/vulgor/vul_sigh.png"
image vul smirk = "images/sprites/vulgor/vul_smirk.png"
image vul smirk h = "images/sprites/vulgor/vul_smirk_h.png"
image vul smile = "images/sprites/vulgor/vulgor_smile.png"
image vul smile e = "images/sprites/vulgor/vul_smile_e.png"
image vul smile p = "images/sprites/vulgor/vul_smile_p.png"
image vul smile x = "images/sprites/vulgor/vul_smile_x.png"
image vul smile l = "images/sprites/vulgor/vulgor_smile_l.png"
image vul smile u = "images/sprites/vulgor/vulgor_smile_u.png"
image vul smile ue = "images/sprites/vulgor/vul_smile_ue.png"
image vul smile v = "images/sprites/vulgor/vul_smile_v.png"
image vul talk = "images/sprites/vulgor/vulgor_talk.png"
image vul talk ang = "images/sprites/vulgor/vulgor_talk_ang.png"
image vul talk l = "images/sprites/vulgor/vulgor_talk_l.png"
image vul talk lx = "images/sprites/vulgor/vulgor_talk_lx.png"
image vul talk p = "images/sprites/vulgor/vulgor_talk_p.png"
image vul talk pe = "images/sprites/vulgor/vulgor_talk_pe.png"
image vul talk s = "images/sprites/vulgor/vul_talk_s.png"
image vul talk sp = "images/sprites/vulgor/vul_talk_sp.png"
image vul talk se = "images/sprites/vulgor/vul_talk_se.png"
image vul talk sex = "images/sprites/vulgor/vul_talk_sex.png"
image vul talk sep = "images/sprites/vulgor/vul_talk_sep.png"
image vul talk su = "images/sprites/vulgor/vul_talk_su.png"
image vul talk sl = "images/sprites/vulgor/vul_talk_sl.png"
image vul talk sup = "images/sprites/vulgor/vul_talk_sup.png"
image vul talk spe = "images/sprites/vulgor/vul_talk_spe.png"
image vul talk sur = "images/sprites/vulgor/vul_talk_sur.png"
image vul talk pl = "images/sprites/vulgor/vulgor_talk_pl.png"
image vul talk lp = "images/sprites/vulgor/vul_talk_lp.png"
image vul talk pu = "images/sprites/vulgor/vulgor_talk_pu.png"
image vul talk x = "images/sprites/vulgor/vulgor_talk_x.png"
image vul talk e = "images/sprites/vulgor/vul_talk_e.png"
image vul talk ex = "images/sprites/vulgor/vul_talk_ex.png"
image vul talk pe = "images/sprites/vulgor/vul_talk_pe.png"
image vul talk ep = "images/sprites/vulgor/vul_talk_ep.png"
image vul unamused = "images/sprites/vulgor/vulgor_unamused.png"
image vul unamused u = "images/sprites/vulgor/vulgor_unamused_u.png"
image vul bemused ltx = "images/sprites/vulgor/vul_uncomfortable_ltx.png"
image vul unhappy = "images/sprites/vulgor/vulgor_unhappy.png"
image vul unhappy e = "images/sprites/vulgor/vulgor_unhappy_e.png"
image vul unhappy l = "images/sprites/vulgor/vulgor_unhappy_l.png"
image vul unhappy x = "images/sprites/vulgor/vulgor_unhappy_x.png"
image vul whisper s = "images/sprites/vulgor/vul_whisper_s.png"
image vul whisper sx = "images/sprites/vulgor/vul_whisper_sx.png"
image vul worried = "images/sprites/vulgor/vulgor_worried.png"
image vul worried l = "images/sprites/vulgor/vulgor_worried_l.png"
image vul mutter = "images/sprites/vulgor/vul_mutter.png"
image vul wink = "images/sprites/vulgor/vul_wink.png"
image vul unhappy r = "images/sprites/vulgor/vul_unhappy_r.png"
image vul talk sue = "images/sprites/vulgor/vul_talk_sue.png"
image vul surprised lt = "images/sprites/vulgor/vul_surprised_lt.png"


image vul right eyeroll = "images/sprites/vulgor_right/vul_eyeroll.png"
image vul right growl ex = "images/sprites/vulgor_right/vul_growl_ex.png"
image vul right growl r = "images/sprites/vulgor_right/vul_growl_r.png"
image vul right growl k = "images/sprites/vulgor_right/vul_growl_k.png"
image vul right growl rk = "images/sprites/vulgor_right/vul_growl_rk.png"
image vul right intrigued = "images/sprites/vulgor_right/vul_intrigued.png"
image vul right intrigued r = "images/sprites/vulgor_right/vul_intrigued_r.png"
image vul right intrigued t = "images/sprites/vulgor_right/vul_intrigued_t.png"
image vul right neutral ex = "images/sprites/vulgor_right/vul_neutral_ex.png"
image vul right neutral p = "images/sprites/vulgor_right/vul_neutral_p.png"
image vul right neutral r = "images/sprites/vulgor_right/vul_neutral_r.png"
image vul right neutral x = "images/sprites/vulgor_right/vul_neutral_x.png"
image vul right neutral rx = "images/sprites/vulgor_right/vul_neutral_rx.png"
image vul right sigh = "images/sprites/vulgor_right/vul_sigh.png"
image vul right smile = "images/sprites/vulgor_right/vul_smile.png"
image vul right smile e = "images/sprites/vulgor_right/vul_smile_e.png"
image vul right smile r = "images/sprites/vulgor_right/vul_smile_r.png"
image vul right smirk e = "images/sprites/vulgor_right/vul_smirk_e.png"
image vul right smirk ex = "images/sprites/vulgor_right/vul_smirk_ex.png"
image vul right smirk rx = "images/sprites/vulgor_right/vul_smirk_rx.png"
image vul right smirk tlp = "images/sprites/vulgor_right/vul_smirk_tlp.png"
image vul right smirk tr = "images/sprites/vulgor_right/vul_smirk_tr.png"
image vul right smirk x = "images/sprites/vulgor_right/vul_smirk_x.png"
image vul right talk e = "images/sprites/vulgor_right/vul_talk_e.png"
image vul right talk ex = "images/sprites/vulgor_right/vul_talk_ex.png"
image vul right talk p = "images/sprites/vulgor_right/vul_talk_p.png"
image vul right talk rp = "images/sprites/vulgor_right/vul_talk_rp.png"
image vul right talk sex = "images/sprites/vulgor_right/vul_talk_sex.png"
image vul right talk sp = "images/sprites/vulgor_right/vul_talk_sp.png"
image vul right talk spl = "images/sprites/vulgor_right/vul_talk_spl.png"
image vul right talk xl = "images/sprites/vulgor_right/vul_talk_xl.png"
image vul right talk xr = "images/sprites/vulgor_right/vul_talk_xr.png"
image vul right uncomfortable = "images/sprites/vulgor_right/vul_uncomfortable.png"
image vul right uncomfortable e = "images/sprites/vulgor_right/vul_uncomfortable_e.png"
image vul right uncomfortable r = "images/sprites/vulgor_right/vul_uncomfortable_r.png"
image vul right unhappy l = "images/sprites/vulgor_right/vul_unhappy_l.png"
image vul right unhappy r = "images/sprites/vulgor_right/vul_unhappy_r.png"
image vul right worried = "images/sprites/vulgor_right/vul_worried.png"
image vul right worried r = "images/sprites/vulgor_right/vul_worried_r.png"


image ver annoyed = "images/sprites/verissa/ver_annoyed.png"
image ver annoyed t = "images/sprites/verissa/ver_annoyed_t.png"
image ver annoyed l = "images/sprites/verissa/ver_annoyed_l.png"
image ver neutral = "images/sprites/verissa/ver_neutral.png"
image ver neutral l = "images/sprites/verissa/ver_neutral_l.png"
image ver neutral r = "images/sprites/verissa/ver_neutral_r.png"
image ver pouty = "images/sprites/verissa/ver_pouty.png"
image ver sad = "images/sprites/verissa/ver_sad.png"
image ver sad e = "images/sprites/verissa/ver_sad_e.png"
image ver sad et = "images/sprites/verissa/ver_sad_et.png"
image ver sad r = "images/sprites/verissa/ver_sad_r.png"
image ver sad rp = "images/sprites/verissa/ver_sad_rp.png"
image ver sad rpt = "images/sprites/verissa/ver_sad_rpt.png"
image ver sad rt = "images/sprites/verissa/ver_sad_rt.png"
image ver sad t = "images/sprites/verissa/ver_sad_t.png"
image ver sad x = "images/sprites/verissa/ver_sad_x.png"
image ver sad xe = "images/sprites/verissa/ver_sad_xe.png"
image ver sad xet = "images/sprites/verissa/ver_sad_xet.png"
image ver sad xr = "images/sprites/verissa/ver_sad_xr.png"
image ver sad xt = "images/sprites/verissa/ver_sad_xt.png"
image ver eyeroll = "images/sprites/verissa/ver_eyeroll.png"
image ver ang fl = "images/sprites/verissa/ver_ang_fl.png"
image ver shocked = "images/sprites/verissa/ver_shocked.png"
image ver shocked l = "images/sprites/verissa/ver_shocked_l.png"
image ver l annoyed = "images/sprites/verissa/ver_l_annoyed.png"
image ver l annoyed t = "images/sprites/verissa/ver_l_annoyed_t.png"
image ver talk = "images/sprites/verissa/ver_talk.png"
image ver talk e = "images/sprites/verissa/ver_talk_e.png"
image ver talk s = "images/sprites/verissa/ver_talk_s.png"
image ver talk sx = "images/sprites/verissa/ver_talk_sx.png"
image ver talk x = "images/sprites/verissa/ver_talk_x.png"
image ver talk l = "images/sprites/verissa/ver_talk_l.png"
image ver talk lp = "images/sprites/verissa/ver_talk_lp.png"
image ver talk pl = "images/sprites/verissa/ver_talk_pl.png"
image ver talk h = "images/sprites/verissa/ver_talk_h.png"
image ver talk sp = "images/sprites/verissa/ver_talk_sp.png"
image ver thinking t = "images/sprites/verissa/ver_thinking_t.png"
image ver neutral e = "images/sprites/verissa/ver_neutral_e.png"
image ver neutral x = "images/sprites/verissa/ver_neutral_x.png"
image ver uncomfortable = "images/sprites/verissa/ver_uncomfortable.png"
image ver uncomfortable t = "images/sprites/verissa/ver_uncomfortable_t.png"
image ver grumble = "images/sprites/verissa/ver_grumble.png"
image ver grumble p = "images/sprites/verissa/ver_grumble_p.png"
image ver doubtful = "images/sprites/verissa/ver_doubtful.png"
image ver doubtful t = "images/sprites/verissa/ver_doubtful_t.png"
image ver intrigued = "images/sprites/verissa/ver_intrigued.png"
image ver talk ang pl = "images/sprites/verissa/ver_talk_ang_pl.png"
image ver talk ang pr = "images/sprites/verissa/ver_talk_ang_pr.png"
image ver talk ang lp = "images/sprites/verissa/ver_talk_ang_lp.png"
image ver talk ang x = "images/sprites/verissa/ver_talk_ang_x.png"
image ver ang = "images/sprites/verissa/ver_ang.png"
image ver ang r = "images/sprites/verissa/ver_ang_r.png"
image ver ang rp = "images/sprites/verissa/ver_ang_rp.png"
image ver facepalm = "images/sprites/verissa/ver_facepalm.png"
image ver sigh = "images/sprites/verissa/ver_sigh.png"
image ver smile = "images/sprites/verissa/ver_smile.png"
image ver smile e = "images/sprites/verissa/ver_smile_e.png"
image ver smile l = "images/sprites/verissa/ver_smile_l.png"
image ver smile r = "images/sprites/verissa/ver_smile_r.png"
image ver smile et = "images/sprites/verissa/ver_smile_et.png"
image ver smile ex = "images/sprites/verissa/ver_smile_ex.png"
image ver smile tp = "images/sprites/verissa/ver_smile_tp.png"
image ver amused = "images/sprites/verissa/ver_amused.png"
image ver amused p = "images/sprites/verissa/ver_amused_p.png"
image ver amused s = "images/sprites/verissa/ver_amused_s.png"
image ver amused e = "images/sprites/verissa/ver_amused_e.png"
image ver amused et = "images/sprites/verissa/ver_amused_et.png"
image ver question l = "images/sprites/verissa/ver_question_l.png"
image ver curious = "images/sprites/verissa/ver_curious.png"
image ver curious t = "images/sprites/verissa/ver_curious_t.png"
image ver curious tp = "images/sprites/verissa/ver_curious_tp.png"
image ver laugh = "images/sprites/verissa/ver_laugh.png"
image ver wine pouty = "images/sprites/verissa/ver_wine_pouty.png"
image ver wine smile = "images/sprites/verissa/ver_wine_smile.png"
image ver wine laugh = "images/sprites/verissa/ver_wine_laugh.png"
image ver growl p = "images/sprites/verissa/ver_growl_p.png"


image chi growl = "images/sprites/chief/chi_growl.png"
image chi growl l = "images/sprites/chief/chi_growl_l.png"
image chi growl r = "images/sprites/chief/chi_growl_r.png"
image chi look l = "images/sprites/chief/chi_look_l.png"
image chi look r = "images/sprites/chief/chi_look_r.png"
image chi mutter = "images/sprites/chief/chi_mutter.png"
image chi neutral = "images/sprites/chief/chi_neutral.png"
image chi neutral e = "images/sprites/chief/chi_neutral_e.png"
image chi neutral l = "images/sprites/chief/chi_neutral_l.png"
image chi neutral le = "images/sprites/chief/chi_neutral_l.png"
image chi neutral r = "images/sprites/chief/chi_neutral_r.png"
image chi neutral re = "images/sprites/chief/chi_neutral_r.png"
image chi shocked = "images/sprites/chief/chi_shocked.png"
image chi shocked ang = "images/sprites/chief/chi_shocked_ang.png"
image chi smile = "images/sprites/chief/chi_smile.png"
image chi smile e = "images/sprites/chief/chi_smile_e.png"
image chi smile l = "images/sprites/chief/chi_smile_l.png"
image chi smile r = "images/sprites/chief/chi_smile_r.png"
image chi smile re = "images/sprites/chief/chi_smile_re.png"
image chi smile t = "images/sprites/chief/chi_smile_t.png"
image chi smile te = "images/sprites/chief/chi_smile_te.png"
image chi talk = "images/sprites/chief/chi_talk.png"
image chi talk e = "images/sprites/chief/chi_talk_e.png"
image chi talk l = "images/sprites/chief/chi_talk_l.png"
image chi talk le = "images/sprites/chief/chi_talk_l.png"
image chi talk r = "images/sprites/chief/chi_talk_r.png"
image chi talk re = "images/sprites/chief/chi_talk_re.png"
image chi talk rs = "images/sprites/chief/chi_talk_rs.png"
image chi talk rse = "images/sprites/chief/chi_talk_rse.png"
image chi talk s = "images/sprites/chief/chi_talk_s.png"
image chi talk se = "images/sprites/chief/chi_talk_se.png"
image chi talk sl = "images/sprites/chief/chi_talk_sl.png"
image chi talk sr = "images/sprites/chief/chi_talk_sr.png"
image chi worried tl = "images/sprites/chief/chi_worried_tl.png"
image chi curious = "images/sprites/chief/chi_curious.png"


image tan curious = "images/sprites/tano/tan_curious.png"
image tan curious t = "images/sprites/tano/tan_curious_t.png"
image tan curious tp = "images/sprites/tano/tan_curious_tp.png"
image tan curious lt = "images/sprites/tano/tan_curious_lt.png"
image tan curious ltp = "images/sprites/tano/tan_curious_ltp.png"
image tan curious l = "images/sprites/tano/tan_curious_l.png"
image tan doubt = "images/sprites/tano/tan_doubt.png"
image tan eyeroll = "images/sprites/tano/tan_eyeroll.png"
image tan eyeroll p = "images/sprites/tano/tan_eyeroll_p.png"
image tan eyeroll sp = "images/sprites/tano/tan_eyeroll_sp.png"
image tan serious = "images/sprites/tano/tan_serious.png"
image tan serious r = "images/sprites/tano/tan_serious_r.png"
image tan serious rt = "images/sprites/tano/tan_serious_rt.png"
image tan serious t = "images/sprites/tano/tan_serious_t.png"
image tan smile = "images/sprites/tano/tan_smile.png"
image tan smile e = "images/sprites/tano/tan_smile_e.png"
image tan smile v = "images/sprites/tano/tan_smile_v.png"
image tan smile tv = "images/sprites/tano/tan_smile_tv.png"
image tan smile te = "images/sprites/tano/tan_smile_te.png"
image tan smile l = "images/sprites/tano/tan_smile_l.png"
image tan smile ltv = "images/sprites/tano/tan_smile_ltv.png"
image tan smile t = "images/sprites/tano/tan_smile_t.png"
image tan smile tlp = "images/sprites/tano/tan_smile_tlp.png"
image tan wink = "images/sprites/tano/tan_wink.png"
image tan wink p = "images/sprites/tano/tan_wink_p.png"
image tan shocked = "images/sprites/tano/tan_shocked.png"
image tan serious r = "images/sprites/tano/tan_serious_r.png"
image tan serious tf = "images/sprites/tano/tan_serious_tf.png"
image tan serious etp = "images/sprites/tano/tan_serious_etp.png"
image tan sigh = "images/sprites/tano/tan_sigh.png"
image tan sigh ep = "images/sprites/tano/tan_sigh_ep.png"
image tan laugh = "images/sprites/tano/tan_laugh.png"
image tan listen r = "images/sprites/tano/tan_listen_r.png"
image tan growl = "images/sprites/tano/tan_growl.png"
image tan growl l = "images/sprites/tano/tan_growl_l.png"
image tan growl lx = "images/sprites/tano/tan_growl_lx.png"
image tan shocked l = "images/sprites/tano/tan_shocked_l.png"
image tan shrug e = "images/sprites/tano/tan_shrug_e.png"
image tan yell = "images/sprites/tano/tan_yell.png"
image tan unhappy = "images/sprites/tano/tan_unhappy.png"
image tan unhappy l = "images/sprites/tano/tan_unhappy_l.png"
image tan neutral lte = "images/sprites/tano/tan_neutral_lte.png"
image tan neutral ltp = "images/sprites/tano/tan_neutral_ltp.png"
image tan talk p = "images/sprites/tano/tan_talk_p.png"
image tan growl l hard = "images/sprites/tano/tan_growl_l_hard.png"
image tan growl rp = "images/sprites/tano/tan_growl_rp.png"
image tan ang lt = "images/sprites/tano/tan_ang_lt.png"
image tan ang l = "images/sprites/tano/tan_ang_l.png"
image tan ang lx = "images/sprites/tano/tan_ang_lx.png"
image tan worried l = "images/sprites/tano/tan_worried_l.png"
image tan worried = "images/sprites/tano/tan_worried.png"
image tan worried lte = "images/sprites/tano/tan_worried_lte.png"
image tan awkward sle = "images/sprites/tano/tan_awkward_sle.png"
image tan shocked lx = "images/sprites/tano/tan_shocked_lx.png"
image tan neutral e = "images/sprites/tano/tan_neutral_e.png"


image vit smile = "images/sprites/vithyr/vit_smile.png"
image vit smile e = "images/sprites/vithyr/vit_smile_e.png"
image vit smile l = "images/sprites/vithyr/vit_smile_l.png"
image vit smile le = "images/sprites/vithyr/vit_smile_le.png"
image vit talk = "images/sprites/vithyr/vit_talk.png"
image vit talk e = "images/sprites/vithyr/vit_talk_e.png"
image vit talk l = "images/sprites/vithyr/vit_talk_l.png"
image vit talk le = "images/sprites/vithyr/vit_talk_le.png"
image vit talk lp = "images/sprites/vithyr/vit_talk_lp.png"
image vit talk r = "images/sprites/vithyr/vit_talk_r.png"
image vit talk ang = "images/sprites/vithyr/vit_talk_ang.png"
image vit laugh = "images/sprites/vithyr/vit_laugh.png"
image vit laugh p = "images/sprites/vithyr/vit_laugh_p.png"
image vit unhappy = "images/sprites/vithyr/vit_unhappy.png"
image vit unhappy rt = "images/sprites/vithyr/vit_unhappy_rt.png"
image vit neutral = "images/sprites/vithyr/vit_neutral.png"
image vit neutral l = "images/sprites/vithyr/vit_neutral_l.png"
image vit neutral lt = "images/sprites/vithyr/vit_neutral_lt.png"
image vit neutral lte = "images/sprites/vithyr/vit_neutral_lte.png"
image vit dismissive = "images/sprites/vithyr/vit_dismissive.png"


image trs ang x = "images/sprites/tryst/try_ang_x.png"

image trs annoyed = "images/sprites/tryst/try_annoyed.png"
image trs annoyed e = "images/sprites/tryst/try_annoyed_e.png"
image trs annoyed ex = "images/sprites/tryst/try_annoyed_ex.png"
image trs annoyed l = "images/sprites/tryst/try_annoyed_l.png"
image trs annoyed lx = "images/sprites/tryst/try_annoyed_lx.png"
image trs annoyed r = "images/sprites/tryst/try_annoyed_r.png"
image trs annoyed rx = "images/sprites/tryst/try_annoyed_rx.png"
image trs annoyed t = "images/sprites/tryst/try_annoyed_t.png"
image trs annoyed te = "images/sprites/tryst/try_annoyed_te.png"
image trs annoyed tef = "images/sprites/tryst/try_annoyed_tef.png"
image trs annoyed tep = "images/sprites/tryst/try_annoyed_tep.png"
image trs annoyed tex = "images/sprites/tryst/try_annoyed_tex.png"
image trs annoyed tf = "images/sprites/tryst/try_annoyed_tf.png"
image trs annoyed tl = "images/sprites/tryst/try_annoyed_tl.png"
image trs annoyed tlf = "images/sprites/tryst/try_annoyed_tlf.png"
image trs annoyed tlp = "images/sprites/tryst/try_annoyed_tlp.png"
image trs annoyed tlx = "images/sprites/tryst/try_annoyed_tlx.png"
image trs annoyed tp = "images/sprites/tryst/try_annoyed_tp.png"
image trs annoyed tr = "images/sprites/tryst/try_annoyed_tr.png"
image trs annoyed trf = "images/sprites/tryst/try_annoyed_trf.png"
image trs annoyed trp = "images/sprites/tryst/try_annoyed_trp.png"
image trs annoyed trx = "images/sprites/tryst/try_annoyed_trx.png"
image trs annoyed tx = "images/sprites/tryst/try_annoyed_tx.png"
image trs annoyed x = "images/sprites/tryst/try_annoyed_x.png"
image trs bemused = "images/sprites/tryst/try_bemused.png"
image trs bemused lx = "images/sprites/tryst/try_bemused_lx.png"
image trs bemused t = "images/sprites/tryst/try_bemused_t.png"
image trs bemused tp = "images/sprites/tryst/try_bemused_tp.png"
image trs bemused tlp = "images/sprites/tryst/try_bemused_tlp.png"
image trs bemused tx = "images/sprites/tryst/try_bemused_tx.png"
image trs bemused x = "images/sprites/tryst/try_bemused_x.png"

image trs cringe x = "images/sprites/tryst/try_cringe_x.png"

image trs doubtful = "images/sprites/tryst/try_doubtful.png"
image trs doubtful t = "images/sprites/tryst/try_doubtful_t.png"
image trs doubtful tl = "images/sprites/tryst/try_doubtful_tl.png"
image trs doubtful tlp = "images/sprites/tryst/try_doubtful_tlp.png"
image trs doubtful tlx = "images/sprites/tryst/try_doubtful_tlx.png"
image trs doubtful tp = "images/sprites/tryst/try_doubtful_tp.png"
image trs doubtful tx = "images/sprites/tryst/try_doubtful_tx.png"
image trs doubtful x = "images/sprites/tryst/try_doubtful_x.png"
image trs eyeroll = "images/sprites/tryst/try_eyeroll.png"
image trs mutter = "images/sprites/tryst/try_mutter.png"
image trs mutter e = "images/sprites/tryst/try_mutter_e.png"
image trs mutter ep = "images/sprites/tryst/try_mutter_ep.png"
image trs mutter ex = "images/sprites/tryst/try_mutter_ex.png"
image trs mutter l = "images/sprites/tryst/try_mutter_l.png"
image trs mutter lp = "images/sprites/tryst/try_mutter_lp.png"
image trs mutter lx = "images/sprites/tryst/try_mutter_lx.png"
image trs mutter p = "images/sprites/tryst/try_mutter_p.png"
image trs mutter r = "images/sprites/tryst/try_mutter_r.png"
image trs mutter rp = "images/sprites/tryst/try_mutter_rp.png"
image trs mutter rx = "images/sprites/tryst/try_mutter_rx.png"
image trs mutter x = "images/sprites/tryst/try_mutter_x.png"
image trs neutral = "images/sprites/tryst/try_neutral.png"
image trs neutral e = "images/sprites/tryst/try_neutral_e.png"
image trs neutral ex = "images/sprites/tryst/try_neutral_ex.png"
image trs neutral l = "images/sprites/tryst/try_neutral_l.png"
image trs neutral lx = "images/sprites/tryst/try_neutral_lx.png"
image trs neutral r = "images/sprites/tryst/try_neutral_r.png"
image trs neutral rx = "images/sprites/tryst/try_neutral_rx.png"
image trs neutral x = "images/sprites/tryst/try_neutral_x.png"
image trs shocked = "images/sprites/tryst/try_shocked.png"
image trs shocked x = "images/sprites/tryst/try_shocked_x.png"
image trs shrug = "images/sprites/tryst/try_shrug.png"
image trs shrug t = "images/sprites/tryst/try_shrug_t.png"
image trs smile = "images/sprites/tryst/try_smile.png"
image trs smile e = "images/sprites/tryst/try_smile_e.png"
image trs smile ep = "images/sprites/tryst/try_smile_ep.png"
image trs smile ex = "images/sprites/tryst/try_smile_ex.png"
image trs smile l = "images/sprites/tryst/try_smile_l.png"
image trs smile lx = "images/sprites/tryst/try_smile_lx.png"
image trs smile r = "images/sprites/tryst/try_smile_r.png"
image trs smile rx = "images/sprites/tryst/try_smile_rx.png"
image trs smile t = "images/sprites/tryst/try_smile_t.png"
image trs smile te = "images/sprites/tryst/try_smile_te.png"
image trs smile tep = "images/sprites/tryst/try_smile_tep.png"
image trs smile tex = "images/sprites/tryst/try_smile_tex.png"
image trs smile tf = "images/sprites/tryst/try_smile_tf.png"
image trs smile tl = "images/sprites/tryst/try_smile_tl.png"
image trs smile tlp = "images/sprites/tryst/try_smile_tlp.png"
image trs smile tlx = "images/sprites/tryst/try_smile_tlx.png"
image trs smile tp = "images/sprites/tryst/try_smile_tp.png"
image trs smile tr = "images/sprites/tryst/try_smile_tr.png"
image trs smile trp = "images/sprites/tryst/try_smile_trp.png"
image trs smile trx = "images/sprites/tryst/try_smile_trx.png"
image trs smile tx = "images/sprites/tryst/try_smile_tx.png"

image trs smile v = "images/sprites/tryst/try_smile_v.png"

image trs smile x = "images/sprites/tryst/try_smile_x.png"
image trs smirk = "images/sprites/tryst/try_smirk.png"
image trs smirk e = "images/sprites/tryst/try_smirk_e.png"
image trs smirk ex = "images/sprites/tryst/try_smirk_ex.png"
image trs smirk l = "images/sprites/tryst/try_smirk_l.png"
image trs smirk lx = "images/sprites/tryst/try_smirk_lx.png"
image trs smirk r = "images/sprites/tryst/try_smirk_r.png"
image trs smirk rx = "images/sprites/tryst/try_smirk_rx.png"
image trs smirk t = "images/sprites/tryst/try_smirk_t.png"
image trs smirk te = "images/sprites/tryst/try_smirk_te.png"
image trs smirk tep = "images/sprites/tryst/try_smirk_tep.png"
image trs smirk tex = "images/sprites/tryst/try_smirk_tex.png"
image trs smirk tf = "images/sprites/tryst/try_smirk_tf.png"
image trs smirk tl = "images/sprites/tryst/try_smirk_tl.png"
image trs smirk tlp = "images/sprites/tryst/try_smirk_tlp.png"
image trs smirk tlx = "images/sprites/tryst/try_smirk_tlx.png"
image trs smirk tp = "images/sprites/tryst/try_smirk_tp.png"
image trs smirk tr = "images/sprites/tryst/try_smirk_tr.png"
image trs smirk trp = "images/sprites/tryst/try_smirk_trp.png"
image trs smirk trx = "images/sprites/tryst/try_smirk_trx.png"
image trs smirk tx = "images/sprites/tryst/try_smirk_tx.png"
image trs smirk x = "images/sprites/tryst/try_smirk_x.png"

image trs suspicious = "images/sprites/tryst/try_suspicious.png"

image trs talk ang x = "images/sprites/tryst/try_talk_ang_x.png"

image trs talk = "images/sprites/tryst/try_talk.png"
image trs talk e = "images/sprites/tryst/try_talk_e.png"
image trs talk ep = "images/sprites/tryst/try_talk_ep.png"
image trs talk ex = "images/sprites/tryst/try_talk_ex.png"
image trs talk l = "images/sprites/tryst/try_talk_l.png"
image trs talk lp = "images/sprites/tryst/try_talk_lp.png"
image trs talk lx = "images/sprites/tryst/try_talk_lx.png"
image trs talk p = "images/sprites/tryst/try_talk_p.png"
image trs talk r = "images/sprites/tryst/try_talk_r.png"
image trs talk rp = "images/sprites/tryst/try_talk_rp.png"
image trs talk rx = "images/sprites/tryst/try_talk_rx.png"
image trs talk s = "images/sprites/tryst/try_talk_s.png"
image trs talk se = "images/sprites/tryst/try_talk_se.png"
image trs talk sep = "images/sprites/tryst/try_talk_sep.png"
image trs talk sex = "images/sprites/tryst/try_talk_sex.png"
image trs talk sf = "images/sprites/tryst/try_talk_sf.png"
image trs talk sl = "images/sprites/tryst/try_talk_sl.png"
image trs talk slp = "images/sprites/tryst/try_talk_slp.png"
image trs talk slx = "images/sprites/tryst/try_talk_slx.png"
image trs talk sp = "images/sprites/tryst/try_talk_sp.png"
image trs talk sr = "images/sprites/tryst/try_talk_sr.png"
image trs talk srp = "images/sprites/tryst/try_talk_srp.png"
image trs talk srx = "images/sprites/tryst/try_talk_srx.png"
image trs talk sx = "images/sprites/tryst/try_talk_sx.png"
image trs talk x = "images/sprites/tryst/try_talk_x.png"
image trs uncomfortable = "images/sprites/tryst/try_uncomfortable.png"
image trs uncomfortable e = "images/sprites/tryst/try_uncomfortable_e.png"
image trs uncomfortable ex = "images/sprites/tryst/try_uncomfotable_ex.png"
image trs uncomfortable t = "images/sprites/tryst/try_uncomfortable_t.png"
image trs uncomfortable tp = "images/sprites/tryst/try_uncomfortable_tp.png"
image trs uncomfortable tx = "images/sprites/tryst/try_uncomfortable_tx.png"
image trs uncomfortable x = "images/sprites/tryst/try_uncomfortable_x.png"
image trs worried = "images/sprites/tryst/try_worried.png"
image trs worried e = "images/sprites/tryst/try_worried_e.png"
image trs worried ex = "images/sprites/tryst/try_worried_ex.png"
image trs worried l = "images/sprites/tryst/try_worried_l.png"
image trs worried lx = "images/sprites/tryst/try_worried_lx.png"
image trs worried r = "images/sprites/tryst/try_worried_r.png"
image trs worried rx = "images/sprites/tryst/try_worried_rx.png"
image trs worried t = "images/sprites/tryst/try_worried_t.png"
image trs worried te = "images/sprites/tryst/try_worried_te.png"
image trs worried tep = "images/sprites/tryst/try_worried_tep.png"
image trs worried tex = "images/sprites/tryst/try_worried_tex.png"
image trs worried tl = "images/sprites/tryst/try_worried_tl.png"
image trs worried tlp = "images/sprites/tryst/try_worried_tlp.png"
image trs worried tlx = "images/sprites/tryst/try_worried_tlx.png"
image trs worried tp = "images/sprites/tryst/try_worried_tp.png"
image trs worried tr = "images/sprites/tryst/try_worried_tr.png"
image trs worried trp = "images/sprites/tryst/try_worried_trp.png"
image trs worried trx = "images/sprites/tryst/try_worried_trx.png"
image trs worried tx = "images/sprites/tryst/try_worried_tx.png"
image trs worried x = "images/sprites/tryst/try_worried_x.png"


image dra neutral = "images/sprites/drair/dra_neutral.png"
image dra shocked = "images/sprites/drair/dra_shocked.png"
image dra surprised = "images/sprites/drair/dra_surprised.png"
image dra talk s = "images/sprites/drair/dra_talk_s.png"
image dra sigh = "images/sprites/drair/dra_sigh.png"
image dra talk e = "images/sprites/drair/dra_talk_e.png"
image dra talk r = "images/sprites/drair/dra_talk_r.png"
image dra uncomfortable s = "images/sprites/drair/dra_uncomfortable_s.png"
image dra worried r = "images/sprites/drair/dra_worried_r.png"
image dra worried rt = "images/sprites/drair/dra_worried_rt.png"


image tyr eyeroll = "images/sprites/tyren/tyr_eyeroll.png"
image tyr mutter l = "images/sprites/tyren/tyr_mutter_l.png"
image tyr neutral = "images/sprites/tyren/tyr_neutral.png"
image tyr neutral l = "images/sprites/tyren/tyr_neutral_l.png"
image tyr shocked = "images/sprites/tyren/tyr_shocked.png"
image tyr smile l = "images/sprites/tyren/tyr_smile_l.png"
image tyr uncomfortable = "images/sprites/tyren/tyr_uncomfortable.png"
image tyr uncomfortable l = "images/sprites/tyren/tyr_uncomfortable_l.png"
image tyr growl = "images/sprites/tyren/tyr_growl.png"
image tyr growl l = "images/sprites/tyren/tyr_growl_l.png"
image tyr shocked l = "images/sprites/tyren/tyr_shocked_l.png"


image cor ang l = "images/sprites/cora/cor_ang_l.png"
image cor jibbies = "images/sprites/cora/cor_jibbies.png"
image cor neutral l = "images/sprites/cora/cor_neutral_l.png"
image cor mutter l = "images/sprites/cora/cor_mutter_l.png"
image cor shocked l = "images/sprites/cora/cor_shocked_l.png"
image cor smile = "images/sprites/cora/cor_smile.png"
image cor smile e = "images/sprites/cora/cor_smile_e.png"
image cor smile l = "images/sprites/cora/cor_smile_l.png"
image cor smile le = "images/sprites/cora/cor_smile_le.png"
image cor smile t = "images/sprites/cora/cor_smile_t.png"
image cor smile te = "images/sprites/cora/cor_smile_te.png"
image cor smile telp = "images/sprites/cora/cor_smile_telp.png"
image cor smirk l = "images/sprites/cora/cor_smirk_l.png"
image cor smirk le = "images/sprites/cora/cor_smirk_le.png"
image cor smirk lp = "images/sprites/cora/cor_smirk_lp.png"
image cor talk ang lp = "images/sprites/cora/cor_talk_ang_lp.png"
image cor talk l = "images/sprites/cora/cor_talk_l.png"
image cor talk l ang = "images/sprites/cora/cor_talk_l_ang.png"
image cor talk lp = "images/sprites/cora/cor_talk_lp.png"
image cor talk sl = "images/sprites/cora/cor_talk_sl.png"
image cor talk sle = "images/sprites/cora/cor_talk_sle.png"
image cor talk slp = "images/sprites/cora/cor_talk_slp.png"
image cor talk slpr = "images/sprites/cora/cor_talk_slpr.png"
image cor wink p = "images/sprites/cora/cor_wink_p.png"
image cor worried = "images/sprites/cora/cor_worried.png"
image cor worried etp = "images/sprites/cora/cor_worried_etp.png"
image cor worried l = "images/sprites/cora/cor_worried_l.png"
image cor worried lt = "images/sprites/cora/cor_worried_lt.png"
image cor worried lte = "images/sprites/cora/cor_worried_lte.png"
image cor worried ltp = "images/sprites/cora/cor_worried_ltp.png"
image cor worried t = "images/sprites/cora/cor_worried_t.png"


image cor r annoyed r = "images/sprites/cora_right/cor_annoyed_r.png"
image cor r neutral r = "images/sprites/cora_right/cor_neutral_r.png"
image cor r neutral rtp = "images/sprites/cora_right/cor_neutral_rtp.png"
image cor r shocked r = "images/sprites/cora_right/cor_shocked_r.png"
image cor r smile r = "images/sprites/cora_right/cor_smile_r.png"
image cor r smile tp = "images/sprites/cora_right/cor_smile_tp.png"
image cor r talk ang l = "images/sprites/cora_right/cor_talk_ang_l.png"
image cor r talk ang re = "images/sprites/cora_right/cor_talk_ang_re.png"
image cor r talk ang rf = "images/sprites/cora_right/cor_talk_ang_rf.png"
image cor r talk r = "images/sprites/cora_right/cor_talk_r.png"
image cor r talk rs = "images/sprites/cora_right/cor_talk_rs.png"
image cor r talk rse = "images/sprites/cora_right/cor_talk_rse.png"
image cor r worried = "images/sprites/cora_right/cor_worried.png"
image cor r worried r = "images/sprites/cora_right/cor_worried_r.png"
image cor r worried rt = "images/sprites/cora_right/cor_worried_rt.png"
image cor r worried rtp = "images/sprites/cora_right/cor_worried_rtp.png"
image cor r worried rte = "images/sprites/cora_right/cor_worried_rte.png"
image cor r worried t = "images/sprites/cora_right/cor_worried_t.png"


image ald angry = "images/sprites/aldris/ald_angry.png"
image ald angry g = "images/sprites/aldris/ald_angry_g.png"
image ald angry gf = "images/sprites/aldris/ald_angry_gf.png"
image ald angry gp = "images/sprites/aldris/ald_angry_gp.png"
image ald angry gu = "images/sprites/aldris/ald_angry_gu.png"
image ald angry t = "images/sprites/aldris/ald_angry_t.png"
image ald angry tf = "images/sprites/aldris/ald_angry_tf.png"
image ald angry tp = "images/sprites/aldris/ald_angry_tp.png"
image ald angry tu = "images/sprites/aldris/ald_angry_tu.png"
image ald growl = "images/sprites/aldris/ald_growl.png"
image ald growl e = "images/sprites/aldris/ald_growl_e.png"
image ald growl ef = "images/sprites/aldris/ald_growl_ef.png"
image ald growl ep = "images/sprites/aldris/ald_growl_ep.png"
image ald growl eu = "images/sprites/aldris/ald_growl_eu.png"
image ald growl f = "images/sprites/aldris/ald_growl_f.png"
image ald growl l = "images/sprites/aldris/ald_growl_l.png"
image ald growl lf = "images/sprites/aldris/ald_growl_lf.png"
image ald growl lp = "images/sprites/aldris/ald_growl_lp.png"
image ald growl lu = "images/sprites/aldris/ald_growl_lu.png"
image ald growl p = "images/sprites/aldris/ald_growl_p.png"
image ald growl r = "images/sprites/aldris/ald_growl_r.png"
image ald growl rf = "images/sprites/aldris/ald_growl_rf.png"
image ald growl rp = "images/sprites/aldris/ald_growl_rp.png"
image ald growl ru = "images/sprites/aldris/ald_growl_ru.png"
image ald growl u = "images/sprites/aldris/ald_growl_u.png"
image ald neutral = "images/sprites/aldris/ald_neutral.png"
image ald neutral e = "images/sprites/aldris/ald_neutral_e.png"
image ald neutral l = "images/sprites/aldris/ald_neutral_l.png"
image ald neutral r = "images/sprites/aldris/ald_neutral_r.png"
image ald talk = "images/sprites/aldris/ald_talk.png"
image ald talk e = "images/sprites/aldris/ald_talk_e.png"
image ald talk ef = "images/sprites/aldris/ald_talk_ef.png"
image ald talk ep = "images/sprites/aldris/ald_talk_ep.png"
image ald talk eu = "images/sprites/aldris/ald_talk_eu.png"
image ald talk f = "images/sprites/aldris/ald_talk_f.png"
image ald talk l = "images/sprites/aldris/ald_talk_l.png"
image ald talk lf = "images/sprites/aldris/ald_talk_lf.png"
image ald talk lp = "images/sprites/aldris/ald_talk_lp.png"
image ald talk lu = "images/sprites/aldris/ald_talk_lu.png"
image ald talk p = "images/sprites/aldris/ald_talk_p.png"
image ald talk r = "images/sprites/aldris/ald_talk_r.png"
image ald talk rf = "images/sprites/aldris/ald_talk_rf.png"
image ald talk rp = "images/sprites/aldris/ald_talk_rp.png"
image ald talk ru = "images/sprites/aldris/ald_talk_ru.png"
image ald talk u = "images/sprites/aldris/ald_talk_u.png"


image drn angry = "images/sprites/dran/drn_angry.png"
image drn angry e = "images/sprites/dran/drn_angry_e.png"
image drn angry l = "images/sprites/dran/drn_angry_l.png"
image drn annoyed = "images/sprites/dran/drn_annoyed.png"
image drn annoyed e = "images/sprites/dran/drn_annoyed_e.png"
image drn annoyed l = "images/sprites/dran/drn_annoyed_l.png"
image drn annoyed m = "images/sprites/dran/drn_annoyed_m.png"
image drn annoyed me = "images/sprites/dran/drn_annoyed_me.png"
image drn annoyed ml = "images/sprites/dran/drn_annoyed_ml.png"
image drn annoyed t = "images/sprites/dran/drn_annoyed_t.png"
image drn annoyed tl = "images/sprites/dran/drn_annoyed_tl.png"
image drn growl = "images/sprites/dran/drn_growl.png"
image drn growl e = "images/sprites/dran/drn_growl_e.png"
image drn growl l = "images/sprites/dran/drn_growl_l.png"
image drn intrigued = "images/sprites/dran/drn_intrigued.png"
image drn intrigued l = "images/sprites/dran/drn_intrigued_l.png"
image drn intrigued m = "images/sprites/dran/drn_intrigued_m.png"
image drn intrigued ml = "images/sprites/dran/drn_intrigued_ml.png"
image drn intrigued t = "images/sprites/dran/drn_intrigued_t.png"
image drn intrigued tl = "images/sprites/dran/drn_intrigued_tl.png"
image drn neutral = "images/sprites/dran/drn_neutral.png"
image drn neutral e = "images/sprites/dran/drn_neutral_e.png"
image drn neutral l = "images/sprites/dran/drn_neutral_l.png"
image drn neutral m = "images/sprites/dran/drn_neutral_m.png"
image drn neutral me = "images/sprites/dran/drn_neutral_me.png"
image drn neutral ml = "images/sprites/dran/drn_neutral_ml.png"
image drn talk = "images/sprites/dran/drn_talk.png"
image drn talk e = "images/sprites/dran/drn_talk_e.png"
image drn talk l = "images/sprites/dran/drn_talk_l.png"


image ene neutral = "images/sprites/enelle/ene_neutral.png"
image ene neutral b = "images/sprites/enelle/ene_neutral_b.png"
image ene neutral e = "images/sprites/enelle/ene_neutral_e.png"
image ene neutral r = "images/sprites/enelle/ene_neutral_r.png"
image ene shocked = "images/sprites/enelle/ene_shocked.png"
image ene smile = "images/sprites/enelle/ene_smile.png"
image ene smile b = "images/sprites/enelle/ene_smile_b.png"
image ene smile e = "images/sprites/enelle/ene_smile_e.png"
image ene smile r = "images/sprites/enelle/ene_smile_r.png"
image ene talk = "images/sprites/enelle/ene_talk.png"
image ene talk b = "images/sprites/enelle/ene_talk_b.png"
image ene talk bf = "images/sprites/enelle/ene_talk_bf.png"
image ene talk bp = "images/sprites/enelle/ene_talk_bp.png"
image ene talk e = "images/sprites/enelle/ene_talk_e.png"
image ene talk ef = "images/sprites/enelle/ene_talk_ef.png"
image ene talk ep = "images/sprites/enelle/ene_talk_ep.png"
image ene talk f = "images/sprites/enelle/ene_talk_f.png"
image ene talk p = "images/sprites/enelle/ene_talk_p.png"
image ene talk r = "images/sprites/enelle/ene_talk_r.png"
image ene talk rf = "images/sprites/enelle/ene_talk_rf.png"
image ene talk rp = "images/sprites/enelle/ene_talk_rp.png"
image ene talk s = "images/sprites/enelle/ene_talk_s.png"
image ene talk sb = "images/sprites/enelle/ene_talk_sb.png"
image ene talk sbf = "images/sprites/enelle/ene_talk_sbf.png"
image ene talk sbp = "images/sprites/enelle/ene_talk_sbp.png"
image ene talk se = "images/sprites/enelle/ene_talk_se.png"
image ene talk sef = "images/sprites/enelle/ene_talk_sef.png"
image ene talk sep = "images/sprites/enelle/ene_talk_sep.png"
image ene talk sf = "images/sprites/enelle/ene_talk_sf.png"
image ene talk sp = "images/sprites/enelle/ene_talk_sp.png"
image ene talk sr = "images/sprites/enelle/ene_talk_sr.png"
image ene talk srf = "images/sprites/enelle/ene_talk_srf.png"
image ene talk srp = "images/sprites/enelle/ene_talk_srp.png"
image ene think = "images/sprites/enelle/ene_think.png"
image ene think b = "images/sprites/enelle/ene_think_b.png"
image ene think e = "images/sprites/enelle/ene_think_e.png"
image ene think l = "images/sprites/enelle/ene_think_l.png"
image ene think r = "images/sprites/enelle/ene_think_r.png"
image ene think s = "images/sprites/enelle/ene_think_s.png"
image ene think sb = "images/sprites/enelle/ene_think_sb.png"
image ene think se = "images/sprites/enelle/ene_think_se.png"
image ene think shocked = "images/sprites/enelle/ene_think_shocked.png"
image ene think sl = "images/sprites/enelle/ene_think_sl.png"
image ene think sr = "images/sprites/enelle/ene_think_sr.png"
image ene think t = "images/sprites/enelle/ene_think_t.png"
image ene think tb = "images/sprites/enelle/ene_think_tb.png"
image ene think te = "images/sprites/enelle/ene_think_te.png"
image ene think tl = "images/sprites/enelle/ene_think_tl.png"
image ene think tr = "images/sprites/enelle/ene_think_tr.png"
image ene think ts = "images/sprites/enelle/ene_think_ts.png"
image ene think tsb = "images/sprites/enelle/ene_think_tsb.png"
image ene think tse = "images/sprites/enelle/ene_think_tse.png"
image ene think tsl = "images/sprites/enelle/ene_think_tsl.png"
image ene think tsr = "images/sprites/enelle/ene_think_tsr.png"


image breakfast = "images/sprites/misc/breakfast.png"
image breakfast full = "images/sprites/misc/breakfast_full.png"
image guard neutral = "images/sprites/misc/guard_neutral.png"
image guard uncomfortable = "images/sprites/misc/guard_uncomfortable.png"
image guard growl = "images/sprites/misc/guard_growl.png"
image night guard = "images/sprites/misc/night_guard.png"
image ran squat smile = "images/sprites/misc/ran_squat_smile.png"
image ran squat talk = "images/sprites/misc/ran_squat_talk.png"
image ran squat shock = "images/sprites/misc/ran_squat_shock.png"
image ran squat worry = "images/sprites/misc/ran_squat_worried.png"
image ran squat worry t = "images/sprites/misc/ran_squat_worried_t.png"
image ran sit laugh = "images/sprites/misc/ran_sit_laugh.png"
image ran sit smile = "images/sprites/misc/ran_sit_smile.png"
image pancakes = "images/sprites/misc/pancakes.png"
image cauldron = "images/sprites/misc/cauldron.png"
image table = "images/sprites/misc/table.png"
image chair = "images/sprites/misc/chair.png"
image tart smile = "images/sprites/misc/tart_smile.png"
image tart smile e = "images/sprites/misc/tart_smile_e.png"
image tart talk = "images/sprites/misc/tart_talk.png"
image tart talk e = "images/sprites/misc/tart_talk_e.png"
image counter = "images/sprites/misc/counter.png"
image dandelion = "images/sprites/misc/dandelion.png"
image dandelion n = "images/sprites/misc/dandelion_n.png"
image dandelion nl = "images/sprites/misc/dandelion_nl.png"
image door = "images/sprites/misc/door.png"
image door l = "images/sprites/misc/door_l.png"
image door n = "images/sprites/misc/door_n.png"
image door nl = "images/sprites/misc/door_nl.png"
image entrance = "images/sprites/misc/entrance.png"
image entrance l = "images/sprites/misc/entrance_l.png"
image entrance n = "images/sprites/misc/entrance_n.png"
image entrance nl = "images/sprites/misc/entrance_nl.png"


define m = Character('[mc]', color="#FFFFFF")
define w = Character('Whispers', color="#7a7a7a")
define bw = Character('Black Wolf', color="#800517")
define gw = Character('Grey Wolf', color="#347235")
define s = Character('Stranger', color="#FFFFFF")
define vm = Character('Voices and me', color="#7a7a7a")
define r = Character('Ranok', color="#347235")
define v = Character('Vulgor', color="#800517")
define ve = Character('Verissa', color="#FBB917")
define ow = Character('Ominous Whisper', color="#7a7a7a")
define c = Character('Chief', color="#504A4B")
define t = Character('Tano', color="#56A5EC")
define tr = Character('Tryst', color="#8B4513")
define wl = Character('Wolves', color="#2B1B17")
define vi = Character('Vithyr', color="#694a42")
define g = Character('Girl', color="#BF554A")
define a = Character('Aldris', color="#49858B")
define d = Character('Dran', color="#597274")
define e = Character('Enelle', color="#5B4C45")
define co = Character('Cora', color="#BF554A")
define dr = Character('Drair', color="#505445")
define ty = Character('Tyren', color="#481D1C")


transform far_left:
    xalign -0.4 yalign 1.0
transform zero:
    xalign -0.2 yalign 1.0
transform one:
    xalign -0.1 yalign 1.0
transform two:
    xalign 0.1 yalign 1.0
transform three:
    xalign 0.2 yalign 1.0
transform four:
    xalign 0.3 yalign 1.0
transform five:
    xalign 0.4 yalign 1.0
transform six:
    xalign 0.5 yalign 1.0
transform seven:
    xalign 0.6 yalign 1.0
transform eight:
    xalign 0.7 yalign 1.0
transform nine:
    xalign 0.8 yalign 1.0
transform ten:
    xalign 0.9 yalign 1.0
transform eleven:
    xalign 1.0 yalign 1.0
transform twelve:
    xalign 1.1 yalign 1.0
transform thirteen:
    xalign 1.2 yalign 1.0
transform fourteen:
    xalign 1.3 yalign 1.0
transform fifteen:
    xalign 1.4 yalign 1.0

transform sit_one:
    xalign .0 yalign .5
transform sit_one_stand:
    xalign .0 yalign .1
transform sit_two:
    xalign .7 yalign .5
transform sit_two_stand:
    xalign .7 yalign .1
transform sit_three:
    xalign 1.5 yalign .2
transform sit_three_stand:
    xalign 1.5 yalign .5
transform sit_four:
    xalign -0.9 yalign .2
transform sit_five:
    xalign 1.34 yalign .5
transform sit_five_stand:
    xalign 1.34 yalign .1
transform post:
    xalign .3 yalign -.1
transform post_front:
    xalign .4 yalign .5
transform lap:
    xalign -0.15 yalign .5
transform lap_stand:
    xalign -0.15 yalign .0
transform sit_mid:
    xalign .5 yalign .2

transform in_your_face:
    xalign .5 yalign 1


init:
    $ opening_fade = Fade(2.0, 0, 2.5)
    $ transition_fade = Fade(3.0, 1.0, 2.0)
    $ fade_transition = Fade(1.5, 1.0, 1.5)
    $ medium_dissolve = Dissolve(2.0)
    $ slow_dissolve = Dissolve(3.0)
    $ move = MoveTransition(0.5)
    $ dis = Dissolve(0.15)

transform jumping:
    linear 0.05 yoffset -20
    linear 0.05 yoffset 0

transform pan_right:
    linear 2.5 xalign 1.0

transform pan_left:
    linear 0.0 xoffset -1920
    linear 2.5 xalign -1.0


init:
    $ Vulgor = 0
    $ Caelan = 0
    $ Knife = False
    $ Booze = False
    $ Romance = False
    $ DrinkingBuddy = False
    $ Attack = False


label start:
$ mc = ""
jump b1c1
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
